Testing with jest
CobbyElsonfx/Math-magician pull request #6
Opened 2023-08-30 20:21 UTC by Rafiduzzaman

## Description

This pull request implements the requested changes to the Math Magicians app, including adding unit tests using Jest and React Testing Library, following best practices for JavaScript, and adhering to the Gitflow workflow.

## Changes Made

- Set up React Testing Library as per the official documentation.
- Wrote unit tests for the `operate.js` and `calculate.js` files using Jest.
- Created unit tests for all React components:
  - Used Jest snapshots to test the components.
  - Utilized React Testing Library to simulate user interaction.
- Ensured there are no linter errors and followed JavaScript best practices.
- Documented the changes and test cases in a professional manner.

## Testing

- Ran the full test suite using Jest.
- All tests have been written and executed to ensure the functionality and quality of the codebase.

## Checklist

- [x] Set up React Testing Library.
- [x] Wrote unit tests for `operate.js` and `calculate.js` using Jest.
- [x] Created unit tests for all React components using snapshots and React Testing Library.
- [x] Ensured there are no linter errors and followed JavaScript best practices.
- [x] Documented the changes and test cases.

## Checklist before merging

- [x] Code review
- [x] Tests passing
- [x] Documentation updated
- [x] Followed Gitflow workflow

Thank you!

2023-08-30 21:10 UTC, Felix45 requested changes
Hi @Rafiduzzaman, @CobbyElsonfx & @78fatemanazari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] All the functionalities of the `operate.js` and `calculate.js` are tested using Jest. :white_check_mark: 
- [x] All components have snapshot tests :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:   

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 21:10 UTC, Felix45 commented on src/__test__/components.test.jsx
> +  });
- [ Required ] I think it would be better if you update the snapshot test for the `Calculator` component, currently, when I run all the tests it fails. Please see the screenshot below for more details on this.

## Error when running tests
![Screenshot from 2023-08-30 23-40-21](https://github.com/CobbyElsonfx/Math-magician/assets/16392046/31737c47-cb83-4a0b-84b7-fdb528230a64)

2023-08-30 21:10 UTC, Felix45 commented on src/__test__/components.test.jsx
> +import { render } from '@testing-library/react';
- [ Required ] I think it would be nice if you added more tests using the `react testing library` to simulate user interaction. This would ensure that the application tests a user's journey on the web page. Please see the example code below for an example of how to achieve this, please feel free to add more tests using the `react testing library`.

## Example code
```JavaScript
import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom'
import Navbar from '../components/Navbar';

describe('Testing Calculator Components', () => {
  test('Test UI text', () => {
    render(<Navbar />);
    const linkElement = screen.getByText(/quote/i);
    const linkElementTwo = screen.getByText(/calculator/i);
    expect(linkElement).toBeInTheDocument();
    expect(linkElementTwo).toBeInTheDocument();
  });
});

```

2023-08-30 22:04 UTC, CobbyElsonfx commented on src/__test__/components.test.jsx
> +import { render } from '@testing-library/react';
Alright, thank you   we will see to it that the changes requested will be implemented accordingly

2023-08-31 04:17 UTC, abdulhamiid approved these changes
# :green_circle:  Approved! :partying_face:
Hi Team 👋, 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)
Your project is complete!  There is nothing else to say other than... It's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Write unit tests with React Testing Library.
- ✔️ Write unit tests with snapshots with Jest.

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-31 07:12 UTC, merged